apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: antonmarkov-dbc-spa-ingress
  namespace: antonmarkovdbcspa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts: 
    - dbc.antonmarkov.com
    secretName: selfsigned-cert-tls
  rules:
  - host: dbc.antonmarkov.com 
    http:
      paths:
      - path: /
        backend:
          serviceName: antonmarkov-dbc-spa
          servicePort: 80